code:
  local_dir: $CONFIG_DIR/../../
description: AMLT
environment:
  image: waybaba/rl:diffuser
  setup:
  - echo "setup start..."
  - export UPRJDIR=/mnt/default/
  - export UDATADIR=/mnt/storage/data
  - export UOUTDIR=/mnt/storage/output
  - mkdir -p /mnt/storage/output /mnt/storage/data
  - echo "setup finished!"
  username: waybaba
search:
  job_template:
    command:
    - python entry/entry.py  wandb.buf_dir=true wandb.mode=online seed=1 experiment=plan_guided
      diffusion.epoch=latest policy.scale_grad_by_std=true trainer.use_controller_act=true
      trainer.plan_once=true vis_freq=100 max_render=1 tags=[PlanOnce_ControlAct_CustomDSBest]
      task_name=RL_Diffuser_Plan1  diffusion.dir={diffusion_dir_} policy.scale={policy_scale_}
      trainer.custom_target={trainer_custom_target_} policy.t_stopgrad={policy_t_stopgrad_}
      guide._target_={guide__target__}
    name: RL_Delayed_{experiment_name:s}_{auto:5s}
    sku: G1-P100
  max_trials: 10000
  params:
  - name: diffusion_dir_
    values:
    - /mnt/storage/output/hydra_log/RL_Diffuser/multiruns/2023-07-19_07-29-30_642861
    - /mnt/storage/output/hydra_log/RL_Diffuser/runs/2023-07-26_14-35-36_761657
    - /mnt/storage/output/hydra_log/RL_Diffuser/runs/2023-07-26_14-34-46_609866
  - name: policy_scale_
    values:
    - 0.001
    - 0.0001
    - 5.0e-05
    - 1.0e-05
  - name: trainer_custom_target_
    values:
    - 2wayAv1
    - 2wayAv2
  - name: policy_t_stopgrad_
    values:
    - 0
    - 4
    - 10
    - 15
    - -4
    - -10
    - -15
  - name: guide__target__
    values:
    - diffuser.sampling.NoTrainGuideHalfShorter
    - diffuser.sampling.NoTrainGuideHalfLonger
    - diffuser.sampling.NoTrainGuideXLower
    - diffuser.sampling.NoTrainGuideXHigher
    - diffuser.sampling.NoTrainGuideYLower
    - diffuser.sampling.NoTrainGuideYHigher
    - diffuser.sampling.NoTrainGuideShorter
    - diffuser.sampling.NoTrainGuideLonger
  type: grid
storage:
  input:
    container_name: v-wangwei1
    local_dir: /mnt/storage
    mount_dir: /mnt/storage
    storage_account_name: resrchvc4data
target:
  name: msrresrchvc
  service: singularity
